- repository: autowarefoundation/autoware
  files:
    - source: .github/dependabot.yaml
    - source: .github/stale.yml
    - source: .github/workflows/github-release.yaml
    - source: .github/workflows/pre-commit.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml

- repository: autowarefoundation/autoware-documentation
  files:
    - source: .github/workflows/deploy-docs.yaml
    - source: .github/workflows/delete-closed-pr-docs.yaml
    - source: .pre-commit-config.yaml
    - source: mkdocs.yaml
      pre-commands: |
        sd "Autoware Documentation" "Kenji Miyake's Tech Articles" {source}
        sd "The Autoware Foundation" "Kenji Miyake" {source}
        sd "autowarefoundation" "kenji-miyake" {source}
        sd "autoware-foundation.png" "icon.png" {source}
        sd "autoware-documentation" "tech-articles" {source}
        sd "repo_url: .*" "repo_url: https://github.com/kenji-miyake/tech-articles" {source}
